global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<VM_HostOnlyIP>:9100']
        labels:
          vm: 'ubuntu'
      - targets: ['<VM_HostOnlyIP>:9100']
        labels:
          vm: 'rocky'
